[package]
name = "lighthouse"
version = "0.1.0"
authors = ["Art Eidukas"]
edition = "2018"

[dependencies]
serde = {version = "*", features = ["derive"]}
serde_json = "*"
reqwest = {version = "0.10.1", features = ["blocking", "json"] }
dirs = "*"
dotenv = "*"
ssdp = "*"
clap = "*"


[[bin]]
name = "lh"
path = "src/bin/lighthouse.rs"
